In [1]:
import pandas as pd
import numpy as np 

Room_data=pd.read_csv("C:\\Users\\DIVESH\\Documents\\Occupancy_Estimation.csv")
print(Room_data.head())
print(Room_data['Room_Occupancy_Count'].unique())

         Date      Time  S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  \
0  2017/12/22  10:49:41    24.94    24.75    24.56    25.38       121
1  2017/12/22  10:50:12    24.94    24.75    24.56    25.44       121
2  2017/12/22  10:50:42    25.00    24.75    24.50    25.44       121
3  2017/12/22  10:51:13    25.00    24.75    24.56    25.44       121
4  2017/12/22  10:51:44    25.00    24.75    24.56    25.44       121

   S2_Light  S3_Light  S4_Light  S1_Sound  S2_Sound  S3_Sound  S4_Sound  \
0        34        53        40      0.08      0.19      0.06      0.06
1        33        53        40      0.93      0.05      0.06      0.06
2        34        53        40      0.43      0.11      0.08      0.06
3        34        53        40      0.41      0.10      0.10      0.09
4        34        54        40      0.18      0.06      0.06      0.06

   S5_CO2  S5_CO2_Slope  S6_PIR  S7_PIR  Room_Occupancy_Count
0     390      0.769231       0       0                     1
1     390      0.646154       0       0                     1
2     390      0.519231       0       0                     1
3     390      0.388462       0       0                     1
4     390      0.253846       0       0                     1
[1 2 3 0]

In [2]:
Room_data.shape

(10129, 19)

In [3]:
Room_data.describe(include='all')

,Date,Time,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR,Room_Occupancy_Count
count,10129,10129,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.00000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000,10129.000000
unique,7,10129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2017/12/23,10:49:41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2779,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,25.454012,25.546059,25.056621,25.754125,25.445059,26.01629,34.248494,13.220259,0.168178,0.120066,0.158119,0.103840,460.860401,-0.004830,0.090137,0.079574,0.398559
std,NaN,NaN,0.351351,0.586325,0.427283,0.356434,51.011264,67.30417,58.400744,19.602219,0.316709,0.266503,0.413637,0.120683,199.964940,1.164990,0.286392,0.270645,0.893633
min,NaN,NaN,24.940000,24.750000,24.440000,24.940000,0.000000,0.00000,0.000000,0.000000,0.060000,0.040000,0.040000,0.050000,345.000000,-6.296154,0.000000,0.000000,0.000000
25%,NaN,NaN,25.190000,25.190000,24.690000,25.440000,0.000000,0.00000,0.000000,0.000000,0.070000,0.050000,0.060000,0.060000,355.000000,-0.046154,0.000000,0.000000,0.000000
50%,NaN,NaN,25.380000,25.380000,24.940000,25.750000,0.000000,0.00000,0.000000,0.000000,0.080000,0.050000,0.060000,0.080000,360.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,25.630000,25.630000,25.380000,26.000000,12.000000,14.00000,50.000000,22.000000,0.080000,0.060000,0.070000,0.100000,465.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,26.380000,29.000000,26.190000,26.560000,165.000000,258.00000,280.000000,74.000000,3.880000,3.440000,3.670000,3.400000,1270.000000,8.980769,1.000000,1.000000,3.000000

In [44]:
x = Room_data[[ 'S1_Temp' , 'S2_Temp' , 'S3_Temp' , 'S4_Temp' , 'S1_Light' , 'S2_Light' , 'S3_Light' , 'S4_Light' , 'S1_Sound' , 'S2_Sound' , 'S3_Sound' , 'S4_Sound' , 'S5_CO2' ,'S5_CO2_Slope' ]]
y= Room_data[['S6_PIR', 'S7_PIR','Room_Occupancy_Count']]

In [47]:
print(y)

       S6_PIR  S7_PIR  Room_Occupancy_Count
0           0       0                     1
1           0       0                     1
2           0       0                     1
3           0       0                     1
4           0       0                     1
...       ...     ...                   ...
10124       0       0                     0
10125       0       0                     0
10126       0       0                     0
10127       0       0                     0
10128       0       0                     0

[10129 rows x 3 columns]

In [48]:
print(x)

       S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  S2_Light  S3_Light  \
0        24.94    24.75    24.56    25.38       121        34        53
1        24.94    24.75    24.56    25.44       121        33        53
2        25.00    24.75    24.50    25.44       121        34        53
3        25.00    24.75    24.56    25.44       121        34        53
4        25.00    24.75    24.56    25.44       121        34        54
...        ...      ...      ...      ...       ...       ...       ...
10124    25.06    25.13    24.69    25.31         6         7        33
10125    25.06    25.06    24.69    25.25         6         7        34
10126    25.13    25.06    24.69    25.25         6         7        34
10127    25.13    25.06    24.69    25.25         6         7        34
10128    25.13    25.06    24.69    25.25         6         7        34

       S4_Light  S1_Sound  S2_Sound  S3_Sound  S4_Sound  S5_CO2  S5_CO2_Slope
0            40      0.08      0.19      0.06      0.06     390      0.769231
1            40      0.93      0.05      0.06      0.06     390      0.646154
2            40      0.43      0.11      0.08      0.06     390      0.519231
3            40      0.41      0.10      0.10      0.09     390      0.388462
4            40      0.18      0.06      0.06      0.06     390      0.253846
...         ...       ...       ...       ...       ...     ...           ...
10124        22      0.09      0.04      0.06      0.08     345      0.000000
10125        22      0.07      0.05      0.05      0.08     345      0.000000
10126        22      0.11      0.05      0.06      0.08     345      0.000000
10127        22      0.08      0.08      0.10      0.08     345      0.000000
10128        22      0.08      0.05      0.06      0.08     345      0.000000

[10129 rows x 14 columns]

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)
print(x_train.shape)
print(y_test.shape)

(9116, 14)
(1013, 3)

In [50]:
from sklearn.neural_network import MLPClassifier

In [53]:
mlp = MLPClassifier(hidden_layer_sizes=(3,2) , activation='relu')
mlp.fit(x_train,y_train)

ValueError: Multioutput target data is not supported with label binarization